AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  ProfileApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: target/AwsLambdaWithSpringBoot-0.0.1-SNAPSHOT.jar
      Handler: com.anil.awslambda.LambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment: 
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 
      Events:
        ProxyResource:
          Type: Api 
          Properties:
            Path: /{proxy+}
            Method: ANY
            
#Outputs:
#  ProfileApi:
#    Description: URL for application
#    Value: !Sub 'https://${ProfileApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/users'
#    Export:
#      Name: ProfileApi